name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup OCaml
        uses: avsm/setup-ocaml@v2

      - name: Install Opam Packages
        run: opam install ocaml-vdom

      - name: Build
        run: opam exec -- dune build --profile release
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
